export interface Agent {
  name: string;
  title: string;
  phone: string;
  email: string;
  photo: string;
  slug: string;
  bio: string[];
}

export const agents: Agent[] = [
  {
    name: 'Jay Lesky',
    title: 'Founder/REALTOR®',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/TEAM_JAY_LESKY.jpg',
    slug: 'jay-lesky',
    bio: [
      "Introducing Jay, the dynamic force behind Pay It Forward Realty, proudly hailing from the vibrant city of Brantford. With a passion for sales and customer service that runs in his veins, Jay's journey began at the tender age of 5, assisting in managing one of his parents' thriving retail franchises. His early exposure to the world of commerce set the stage for a remarkable career defined by innovation and success. From crafting sales scripts for industry giants like Microsoft and Nextel, scripts that still resonate in boardrooms today, to achieving unprecedented ranks in home-based businesses, Jay's trajectory in the business world has been nothing short of extraordinary. His entrepreneurial spirit led him to helm a multi-million-dollar marketing and direct sales company, expanding its reach globally. Since 2003, Jay has navigated the real estate landscape in Brantford and its environs, honing his expertise in buying and selling properties.",
      "Motivated by a profound desire to empower others, Jay founded Pay It Forward Realty with the mission of sharing the invaluable skills, tricks, and techniques that ensure success in real estate endeavours. In a rapidly evolving market, Jay recognizes the crucial elements for triumph: experience, work ethic, communication, networking, and a comprehensive arsenal of marketing skills. The Pay It Forward Real Estate Team stands out in today's competitive market, strategically positioning properties before they hit MLS and Realtor.ca, reaching an extensive audience of 100,000s.",
      "Jay's commitment to community service finds expression in his belief that a team, united in purpose, will always outperform an individual—especially in the dynamic realm of real estate. His mantra, \"Why have one realtor when you can have 10 for the same price,\" reflects his dedication to delivering unparalleled service and results. Join Jay and the Pay It Forward Realty Team on the exciting journey of real estate success, where innovation, expertise, and community spirit converge for a winning combination.",
    ],
  },
  {
    name: 'Jake Eivers',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/JAKEEIVERS1.jpg',
    slug: 'jake-eivers',
    bio: [],
  },
  {
    name: 'Melanie Laracy',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/About/MELANIELARACY1.jpg',
    slug: 'melanie-laracy',
    bio: [],
  },
  {
    name: 'Dina Dalia',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/DINADALIA1.jpg',
    slug: 'dina-dalia',
    bio: [],
  },
  {
    name: 'Mackenzie Cole',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/MACKENZIECOLE1.jpg',
    slug: 'mackenzie-cole',
    bio: [],
  },
  {
    name: 'Matt Dickens',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/TEAM_MATT_DICKENS.jpg',
    slug: 'matt-dickens',
    bio: [],
  },
  {
    name: 'Jake Laracy',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/About/JAKELARACY1.jpg',
    slug: 'jake-laracy',
    bio: [],
  },
  {
    name: 'Brad Lovell',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/TEAM_BRAD_LOVELL.jpg',
    slug: 'brad-lovell',
    bio: [],
  },
  {
    name: 'Sarah Szabo',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/SARAHSZABO1.jpg',
    slug: 'sarah-szabo',
    bio: [],
  },
  {
    name: 'Kristie Ferraccioli',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/TEAM_KRISTIE_FERRACCIOLI.jpg',
    slug: 'kristie-ferraccioli',
    bio: [],
  },
  {
    name: 'Eric Gaudreau',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/ERICGAUDREAU1.jpg',
    slug: 'eric-gaudreau',
    bio: [],
  },
  {
    name: 'Leisha Miller-Bradley',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/LEISHAMILLER-BRADLEY1.jpg',
    slug: 'leisha-miller-bradley',
    bio: [],
  },
  {
    name: 'Ryan Kirkpatrick',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/RYANKIRKPATRICK1.jpg',
    slug: 'ryan-kirkpatrick',
    bio: [],
  },
  {
    name: 'Tonia Cheevers',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/About/Tonia%20Cheevers.webp',
    slug: 'tonia-cheevers',
    bio: [],
  },
  {
    name: 'Amy Ditchburn',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/AMYDITCHBURN.webp',
    slug: 'amy-ditchburn',
    bio: [],
  },
  {
    name: 'Katelyne Schram',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/About/_R6_2942wb.webp',
    slug: 'katelyne-schram',
    bio: [],
  },
  {
    name: 'Vaibhav Dhutti',
    title: 'Sales Representative',
    phone: '(519) 757-7439',
    email: 'info@payitforwardrealty.ca',
    photo: 'https://cdn-websites.agentlocator.ca/18723/Menu/VAIBHAVDHUTTI.jpg',
    slug: 'vaibhav-dhutti',
    bio: [],
  },
];
